// Code generated by wunderctl. DO NOT EDIT.

import type { ClientOperationErrors, GraphQLError } from "@wundergraph/sdk/client";

export type OperationErrors = {
	listTodos: ListTodosErrors;
	subLeaderboard: SubLeaderboardErrors;
	subscribeMe: SubscribeMeErrors;
	updateMe: UpdateMeErrors;
};

export type ListTodosErrors = ClientOperationErrors;
export type SubLeaderboardErrors = ClientOperationErrors;
export type SubscribeMeErrors = ClientOperationErrors;
export type UpdateMeErrors = ClientOperationErrors;
