// Code generated by wunderctl. DO NOT EDIT.

import type { ClientOperationErrors, GraphQLError } from "@wundergraph/sdk/client";

export type OperationErrors = {
	createInvite: CreateInviteErrors;
	listSubscribers: ListSubscribersErrors;
	listTodos: ListTodosErrors;
	queryLeaderboard: QueryLeaderboardErrors;
	queryMe: QueryMeErrors;
	subLeaderboard: SubLeaderboardErrors;
	subMe: SubMeErrors;
	toggleNewsletter: ToggleNewsletterErrors;
	updateMe: UpdateMeErrors;
};

export type CreateInviteErrors = ClientOperationErrors;
export type ListSubscribersErrors = ClientOperationErrors;
export type ListTodosErrors = ClientOperationErrors;
export type QueryLeaderboardErrors = ClientOperationErrors;
export type QueryMeErrors = ClientOperationErrors;
export type SubLeaderboardErrors = ClientOperationErrors;
export type SubMeErrors = ClientOperationErrors;
export type ToggleNewsletterErrors = ClientOperationErrors;
export type UpdateMeErrors = ClientOperationErrors;
