// Code generated by wunderctl. DO NOT EDIT.

import type { ClientOperationErrors, GraphQLError } from "@wundergraph/sdk/client";

export type OperationErrors = {
	CreateMandate: CreateMandateErrors;
	CreateSubscription: CreateSubscriptionErrors;
	ListSubscriptions: ListSubscriptionsErrors;
	LoadCustomers: LoadCustomersErrors;
	MyNewsletterStatus: MyNewsletterStatusErrors;
	ToggleNewsletter: ToggleNewsletterErrors;
	createInvite: CreateInviteErrors;
	listTodos: ListTodosErrors;
	queryComposer: QueryComposerErrors;
	queryLeaderboard: QueryLeaderboardErrors;
	queryMe: QueryMeErrors;
	queryUserStats: QueryUserStatsErrors;
	subLeaderboard: SubLeaderboardErrors;
	subMe: SubMeErrors;
	updateMe: UpdateMeErrors;
};

export type CreateMandateErrors = ClientOperationErrors;
export type CreateSubscriptionErrors = ClientOperationErrors;
export type ListSubscriptionsErrors = ClientOperationErrors;
export type LoadCustomersErrors = ClientOperationErrors;
export type MyNewsletterStatusErrors = ClientOperationErrors;
export type ToggleNewsletterErrors = ClientOperationErrors;
export type CreateInviteErrors = ClientOperationErrors;
export type ListTodosErrors = ClientOperationErrors;
export type QueryComposerErrors = ClientOperationErrors;
export type QueryLeaderboardErrors = ClientOperationErrors;
export type QueryMeErrors = ClientOperationErrors;
export type QueryUserStatsErrors = ClientOperationErrors;
export type SubLeaderboardErrors = ClientOperationErrors;
export type SubMeErrors = ClientOperationErrors;
export type UpdateMeErrors = ClientOperationErrors;
