// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Card: typeof import("./src/lib/components/Card.svelte")["default"]
    const CardSelectInput: typeof import("./src/lib/components/CardSelectInput.svelte")["default"]
    const Composer: typeof import("./src/lib/components/Composer.svelte")["default"]
    const ComposerForm: typeof import("./src/lib/components/ComposerForm.svelte")["default"]
    const DateRangeInput: typeof import("./src/lib/components/DateRangeInput.svelte")["default"]
    const Header: typeof import("./src/lib/components/Header.svelte")["default"]
    const HelloEarth: typeof import("./src/lib/components/HelloEarth.svelte")["default"]
    const Nav: typeof import("./src/lib/components/Nav.svelte")["default"]
    const NumberInput: typeof import("./src/lib/components/NumberInput.svelte")["default"]
    const SelectInput: typeof import("./src/lib/components/SelectInput.svelte")["default"]
    const SkeletonAppBar: typeof import("@skeletonlabs/skeleton")["AppBar"]
    const SkeletonAppShell: typeof import("@skeletonlabs/skeleton")["AppShell"]
    const SkeletonDrawer: typeof import("@skeletonlabs/skeleton")["Drawer"]
    const SliderInput: typeof import("./src/lib/components/SliderInput.svelte")["default"]
    const Stepper: typeof import("./src/lib/components/Stepper.svelte")["default"]
    const SubHeader: typeof import("./src/lib/components/SubHeader.svelte")["default"]
    const TextAreaInput: typeof import("./src/lib/components/TextAreaInput.svelte")["default"]
    const TextInput: typeof import("./src/lib/components/TextInput.svelte")["default"]
    const ToggleInput: typeof import("./src/lib/components/ToggleInput.svelte")["default"]
}

export {}
