# This file provides autocompletion in .graphql files
# Some IDEs, like VS code require this file to be at the
# root of your workspace. If you move it around, make sure
# to update schema and documents with the new paths.
schema: '.wundergraph/generated/wundergraph.schema.graphql'
documents: '.wundergraph/operations/**/*.graphql'
extensions:
  endpoint:
    introspect: false
    url: 'https://127.0.0.1:9991/graphql'
    headers:
      user-agent: 'WunderGraph Client'
